title: Introduction to Regression Models
author: Jan Kirenz
logo: logo.png

execute:
  execute_notebooks: cache #force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/kirenz/regression  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Colab
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""